"use client";
import {createClient} from "@supabase/supabase-js";
import {useEffect,useMemo,useState} from "react";
import {supabaseClient} from "./supabase-client";
type Venue={id:number;name:string};type Profile={business_id:number;role:string;venue_id:number|null};type Day={date:string;start:string;end:string;holiday?:boolean};type Worker={id:string;name:string;startDate:string;regular:string;weekend:string;holiday:string;days:Day[]};
const pad=(n:number)=>String(n).padStart(2,"0"),iso=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,add=(d:Date,n:number)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x},monday=()=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return iso(d)},dayNames=["T2","T3","T4","T5","T6","T7","CN"];
const hours=(a:string,b:string)=>{if(!a||!b)return 0;const [ah,am]=a.split(":").map(Number),[bh,bm]=b.split(":").map(Number);let m=bh*60+bm-ah*60-am;if(m<0)m+=1440;return Math.round(m/6)/10};
const newWorker=(week:string):Worker=>{const d=new Date(week+"T12:00:00");return{id:crypto.randomUUID(),name:"",startDate:week,regular:"",weekend:"",holiday:"",days:Array.from({length:7},(_,i)=>({date:iso(add(d,i)),start:"",end:""}))}};
export default function ContractorWeeklyPayroll({profile,venues,defaultVenueId,onNotice,onSubmitted}:{profile:Profile|null;venues:Venue[];defaultVenueId:string;onNotice:(s:string)=>void;onSubmitted?:()=>void|Promise<void>}){
 const initial=monday(),[week,setWeek]=useState(initial),[venue,setVenue]=useState(defaultVenueId),[department,setDepartment]=useState<"game"|"water">("game"),[workers,setWorkers]=useState<Worker[]>(()=>[newWorker(initial)]),[saving,setSaving]=useState(false),[sent,setSent]=useState(false);
 const db=supabaseClient,dates=useMemo(()=>Array.from({length:7},(_,i)=>add(new Date(week+"T12:00:00"),i)),[week]),storageKey=`contractor-payroll:${profile?.business_id||0}:${venue}:${department}:${week}`;
 useEffect(()=>{if(defaultVenueId)setVenue(defaultVenueId)},[defaultVenueId]);useEffect(()=>{const raw=localStorage.getItem(storageKey);if(raw)try{const data=JSON.parse(raw);setWorkers(data.rows?.length?data.rows:[newWorker(week)]);setSent(Boolean(data.sent));return}catch{}setWorkers([newWorker(week)]);setSent(false)},[storageKey,week]);useEffect(()=>{localStorage.setItem(storageKey,JSON.stringify({rows:workers,sent}))},[storageKey,workers,sent]);
 const edit=(id:string,patch:Partial<Worker>)=>{setSent(false);setWorkers(list=>list.map(w=>w.id===id?{...w,...patch}:w))},editDay=(id:string,index:number,patch:Partial<Day>)=>{setSent(false);setWorkers(list=>list.map(w=>w.id===id?{...w,days:w.days.map((d,i)=>i===index?{...d,...patch}:d)}:w))};
 const totalHoursOf=(w:Worker)=>w.days.reduce((s,d)=>s+hours(d.start,d.end),0),payOf=(w:Worker)=>w.days.reduce((s,d,i)=>s+hours(d.start,d.end)*(Number(d.holiday?w.holiday:i>4?w.weekend:w.regular)||0),0),allHours=workers.reduce((s,w)=>s+totalHoursOf(w),0),allPay=Math.round(workers.reduce((s,w)=>s+payOf(w),0));
 async function submit(){if(!profile||!venue){onNotice("Vui lòng chọn sân khấu.");return}const valid=workers.filter(w=>w.name.trim()&&totalHoursOf(w)>0);if(!valid.length||allPay<=0){onNotice("Vui lòng nhập tên, giờ làm và đơn giá.");return}setSaving(true);const {data:{user}}=await db.auth.getUser(),detail=valid.map(w=>`${w.name.trim()}: ${totalHoursOf(w)} giờ = ${Math.round(payOf(w)).toLocaleString("vi-VN")} đ`).join("; ");const {error}=await db.from("finance_entries").upsert({client_id:`contractor-${profile.business_id}-${venue}-${department}-${week}`,business_id:profile.business_id,venue_id:Number(venue),shift_id:null,entry_date:iso(dates[6]),entry_type:"expense",category:"payroll",amount:allPay,note:`Lương giờ thuê ngoài · ${department==="game"?"Trò Chơi":"Quán Nước"} · Tuần ${new Date(week+"T12:00:00").toLocaleDateString("vi-VN")}–${dates[6].toLocaleDateString("vi-VN")} · ${detail}`,status:"pending",created_by:user?.id||null,updated_at:new Date().toISOString()},{onConflict:"client_id"});setSaving(false);if(error){onNotice(error.message);return}setSent(true);onNotice("Đã gửi bảng lương giờ tuần sang Tổng Quan để chủ sở hữu duyệt. Khoản này chỉ được tính vào chi của sân khấu sau khi duyệt.");await onSubmitted?.()}
 return <section className="contractor-payroll">
  <header className="contractor-payroll-hero"><div><p className="eyebrow">NHÂN SỰ THUÊ NGOÀI</p><h3>Bảng Lương Giờ Theo Tuần</h3><span>Nhập giờ lên ca, xuống ca. Tổng giờ và tiền lương được tính tự động.</span></div><div className="contractor-payroll-filters"><label>Sân Khấu<select value={venue} onChange={e=>setVenue(e.target.value)}>{venues.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Bộ Phận<select value={department} onChange={e=>setDepartment(e.target.value as "game"|"water")}><option value="game">Trò Chơi</option><option value="water">Quán Nước</option></select></label><label>Tuần Làm Việc<input type="date" value={week} onChange={e=>setWeek(e.target.value)}/></label></div></header>
  <div className="contractor-workers">{workers.map((worker,workerIndex)=><article className="contractor-worker-card" key={worker.id}><header><span className="worker-number">{workerIndex+1}</span><label className="worker-name">Họ Và Tên<input autoFocus={workerIndex===0} placeholder="Nhập tên nhân sự thuê ngoài" value={worker.name} onChange={e=>edit(worker.id,{name:e.target.value})}/></label><label>Ngày Nhận Việc<input type="date" value={worker.startDate} onChange={e=>edit(worker.id,{startDate:e.target.value})}/></label><button className="remove-worker" onClick={()=>setWorkers(list=>list.filter(item=>item.id!==worker.id))}>×</button></header><div className="contractor-rates"><label><span>Ngày Thường</span><div><input inputMode="numeric" placeholder="0" value={worker.regular} onChange={e=>edit(worker.id,{regular:e.target.value.replace(/\D/g,"")})}/><b>đ/giờ</b></div></label><label><span>Thứ 7 & Chủ Nhật</span><div><input inputMode="numeric" placeholder="0" value={worker.weekend} onChange={e=>edit(worker.id,{weekend:e.target.value.replace(/\D/g,"")})}/><b>đ/giờ</b></div></label><label><span>Ngày Lễ</span><div><input inputMode="numeric" placeholder="0" value={worker.holiday} onChange={e=>edit(worker.id,{holiday:e.target.value.replace(/\D/g,"")})}/><b>đ/giờ</b></div></label></div><div className="contractor-days">{worker.days.map((day,index)=><section className={`contractor-day ${index>4?"weekend":""} ${day.holiday?"holiday":""}`} key={day.date}><header><b>{dayNames[index]}</b><span>{dates[index].toLocaleDateString("vi-VN",{day:"2-digit",month:"2-digit"})}</span></header><div><label>Lên Ca<input type="time" value={day.start} onChange={e=>editDay(worker.id,index,{start:e.target.value})}/></label><label>Xuống Ca<input type="time" value={day.end} onChange={e=>editDay(worker.id,index,{end:e.target.value})}/></label></div><footer><label><input type="checkbox" checked={Boolean(day.holiday)} onChange={e=>editDay(worker.id,index,{holiday:e.target.checked})}/> Ngày lễ</label><strong>{hours(day.start,day.end)} giờ</strong></footer></section>)}</div><footer className="contractor-worker-total"><span>Tổng Giờ Tuần <b>{totalHoursOf(worker)} giờ</b></span><span>Lương Tuần <b>{Math.round(payOf(worker)).toLocaleString("vi-VN")} đ</b></span></footer></article>)}</div>
  <footer className="contractor-payroll-submit"><button className="add-worker" onClick={()=>setWorkers(list=>[...list,newWorker(week)])}>+ Thêm Nhân Sự</button><div><span>Tổng Nhân Sự <b>{workers.filter(w=>w.name.trim()).length}</b></span><span>Tổng Giờ <b>{allHours} giờ</b></span><span>Tổng Lương <b>{allPay.toLocaleString("vi-VN")} đ</b></span></div><button className={sent?"submitted":""} disabled={saving||sent||allPay<=0} onClick={()=>void submit()}>{saving?"Đang Gửi…":sent?"✓ Đang Chờ Duyệt":"Gửi Chủ Sở Hữu Duyệt"}</button></footer>
 </section>
}

