create table if not exists public.costume_plan_references (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  plan_month date not null,
  image_path text not null,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  unique (business_id, plan_month, image_path)
);

create index if not exists costume_plan_references_business_month_idx
  on public.costume_plan_references (business_id, plan_month, created_at desc);
create index if not exists costume_plan_references_created_by_idx
  on public.costume_plan_references (created_by);

alter table public.costume_plan_references enable row level security;

drop policy if exists costume_plan_references_read on public.costume_plan_references;
create policy costume_plan_references_read
on public.costume_plan_references
for select
to authenticated
using (business_id = private.current_business_id());

drop policy if exists costume_plan_references_manage on public.costume_plan_references;
drop policy if exists costume_plan_references_insert on public.costume_plan_references;
create policy costume_plan_references_insert
on public.costume_plan_references
for insert
to authenticated
with check (
  business_id = private.current_business_id()
  and private.current_role() in ('owner', 'manager')
);

drop policy if exists costume_plan_references_update on public.costume_plan_references;
create policy costume_plan_references_update
on public.costume_plan_references
for update
to authenticated
using (business_id = private.current_business_id() and private.current_role() in ('owner', 'manager'))
with check (business_id = private.current_business_id() and private.current_role() in ('owner', 'manager'));

drop policy if exists costume_plan_references_delete on public.costume_plan_references;
create policy costume_plan_references_delete
on public.costume_plan_references
for delete
to authenticated
using (business_id = private.current_business_id() and private.current_role() in ('owner', 'manager'));
