alter table public.venues
  add column if not exists attendance_latitude double precision,
  add column if not exists attendance_longitude double precision,
  add column if not exists attendance_radius_m integer not null default 100 check (attendance_radius_m between 20 and 1000),
  add column if not exists attendance_wifi_ips text[] not null default '{}',
  add column if not exists attendance_configured_at timestamptz;

alter table public.employees
  add column if not exists department text check (department is null or department in ('game','water')),
  add column if not exists pay_type text check (pay_type is null or pay_type in ('monthly','hourly')),
  add column if not exists monthly_salary numeric not null default 0 check (monthly_salary >= 0),
  add column if not exists hourly_rate numeric not null default 0 check (hourly_rate >= 0),
  add column if not exists attendance_enabled boolean not null default false;

create table if not exists public.attendance_sessions (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id),
  venue_id bigint not null references public.venues(id),
  employee_id bigint not null references public.employees(id),
  work_date date not null,
  department text not null check (department in ('game','water')),
  pay_type text not null check (pay_type in ('monthly','hourly')),
  checked_in_at timestamptz not null default now(),
  checked_out_at timestamptz,
  last_heartbeat_at timestamptz not null default now(),
  check_in_latitude double precision not null,
  check_in_longitude double precision not null,
  check_out_reason text check (check_out_reason is null or check_out_reason in ('manual','wifi_timeout','manager_adjustment')),
  status text not null default 'active' check (status in ('active','closed')),
  auto_closed boolean not null default false,
  check_in_ip text,
  check_out_ip text,
  created_by uuid not null references public.profiles(user_id),
  updated_at timestamptz not null default now()
);

create unique index if not exists attendance_one_active_session_per_employee
  on public.attendance_sessions(employee_id) where status='active';
create index if not exists attendance_sessions_venue_date_idx
  on public.attendance_sessions(venue_id,work_date,employee_id);
create index if not exists attendance_sessions_business_idx on public.attendance_sessions(business_id);
create index if not exists attendance_sessions_created_by_idx on public.attendance_sessions(created_by);

alter table public.attendance_sessions enable row level security;
drop policy if exists attendance_select_own_or_manager on public.attendance_sessions;
create policy attendance_select_own_or_manager on public.attendance_sessions for select to authenticated
using (
  exists(select 1 from public.employees e where e.id=employee_id and e.profile_user_id=(select auth.uid()))
  or exists(select 1 from public.profiles p where p.user_id=(select auth.uid()) and p.business_id=attendance_sessions.business_id and p.role in ('owner','manager'))
);
grant select on public.attendance_sessions to authenticated;
grant select on public.venues to authenticated;
grant select on public.employees to authenticated;

create extension if not exists pg_cron with schema extensions;
do $block$ begin
  if exists(select 1 from cron.job where jobname='attendance-auto-close-after-10-minutes') then
    perform cron.unschedule('attendance-auto-close-after-10-minutes');
  end if;
end $block$;
select cron.schedule(
  'attendance-auto-close-after-10-minutes',
  '* * * * *',
  $job$update public.attendance_sessions
        set status='closed',
            checked_out_at=last_heartbeat_at,
            check_out_reason='wifi_timeout',
            auto_closed=true,
            updated_at=now()
      where status='active'
        and last_heartbeat_at <= now() - interval '10 minutes';$job$
);
