alter table public.employees
  add column if not exists payroll_closing_day smallint not null default 31 check (payroll_closing_day between 1 and 31),
  add column if not exists salary_payment_day smallint not null default 10 check (salary_payment_day between 1 and 31),
  add column if not exists responsibility_amount numeric not null default 0 check (responsibility_amount >= 0),
  add column if not exists bonus_amount numeric not null default 0 check (bonus_amount >= 0),
  add column if not exists bonus_advance_eligible boolean not null default false,
  add column if not exists bonus_advance_limit numeric not null default 0 check (bonus_advance_limit >= 0),
  add column if not exists responsibility_target_required boolean not null default false,
  add column if not exists weekly_hourly_rate numeric not null default 25000 check (weekly_hourly_rate >= 0),
  add column if not exists account_access_level smallint not null default 3 check (account_access_level between 1 and 3),
  add column if not exists account_venue_id bigint references public.venues(id),
  add column if not exists job_title text;

alter table public.profiles
  add column if not exists must_change_password boolean not null default false;

create table if not exists public.salary_advance_requests (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id),
  employee_id bigint not null references public.employees(id),
  venue_id bigint not null references public.venues(id),
  request_month date not null check (request_month=date_trunc('month',request_month::timestamp)::date),
  request_type text not null default 'salary' check (request_type in ('salary','bonus')),
  installment smallint not null check (installment in (1,2)),
  amount numeric not null check (amount>0),
  note text,
  status text not null default 'pending' check (status in ('pending','approved','rejected','sent_to_expense','paid')),
  requested_by uuid not null references public.profiles(user_id),
  reviewed_by uuid references public.profiles(user_id),
  reviewed_at timestamptz,
  review_note text,
  finance_entry_id bigint references public.finance_entries(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(business_id,employee_id,request_month,request_type,installment)
);

create or replace function public.validate_salary_advance_request()
returns trigger language plpgsql set search_path=public,pg_temp as $$
declare
  is_eligible boolean;
  max_amount numeric;
  configured_salary numeric;
  requested_total numeric;
  request_count integer;
begin
  select
    bonus_advance_eligible,
    least(coalesce(bonus_advance_limit,0),3000000),
    case pay_type
      when 'monthly' then coalesce(monthly_salary,0)
      when 'weekly' then coalesce(weekly_hourly_rate,0)
      when 'daily' then coalesce(daily_rate,0)
      else coalesce(hourly_rate,0)
    end
  into is_eligible,max_amount,configured_salary
  from public.employees
  where id=new.employee_id and business_id=new.business_id and is_active=true;

  if not found then raise exception 'Không tìm thấy hồ sơ nhân sự đang hoạt động'; end if;

  select coalesce(sum(amount),0),count(*) into requested_total,request_count
  from public.salary_advance_requests
  where business_id=new.business_id
    and employee_id=new.employee_id
    and request_month=new.request_month
    and request_type=new.request_type
    and status<>'rejected'
    and id<>coalesce(new.id,0);

  if new.request_type='salary' then
    if request_count>=2 then raise exception 'Mỗi nhân sự chỉ được ứng lương tối đa 2 lần trong một tháng'; end if;
    if configured_salary>0 and requested_total+new.amount>configured_salary then
      raise exception 'Tổng tiền ứng vượt mức lương đã cấu hình %',configured_salary;
    end if;
  else
    if not coalesce(is_eligible,false) then raise exception 'Nhân sự không có quyền ứng tiền thưởng'; end if;
    if requested_total+new.amount>coalesce(max_amount,0) then
      raise exception 'Tổng tiền ứng thưởng trong tháng vượt giới hạn %',max_amount;
    end if;
  end if;
  return new;
end $$;
drop trigger if exists validate_salary_advance_request_trigger on public.salary_advance_requests;
create trigger validate_salary_advance_request_trigger before insert or update of request_type,amount,employee_id,business_id on public.salary_advance_requests for each row execute function public.validate_salary_advance_request();

create table if not exists public.weekly_payrolls (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id),
  employee_id bigint not null references public.employees(id),
  venue_id bigint not null references public.venues(id),
  week_start date not null,
  week_end date not null,
  total_minutes integer not null default 0 check (total_minutes>=0),
  hourly_rate numeric not null default 25000 check (hourly_rate>=0),
  gross_amount numeric generated always as (round(total_minutes::numeric/60*hourly_rate)) stored,
  closing_at timestamptz,
  payment_due_date date not null,
  status text not null default 'draft' check (status in ('draft','closed','sent_to_expense','paid')),
  finance_entry_id bigint references public.finance_entries(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(business_id,employee_id,week_start)
);

create index if not exists salary_advance_employee_month_idx on public.salary_advance_requests(employee_id,request_month);
create index if not exists salary_advance_status_idx on public.salary_advance_requests(business_id,status,request_month);
create index if not exists weekly_payroll_week_idx on public.weekly_payrolls(business_id,week_start,status);

alter table public.salary_advance_requests enable row level security;
alter table public.weekly_payrolls enable row level security;
grant select,insert,update on public.salary_advance_requests to authenticated;
grant select,insert,update on public.weekly_payrolls to authenticated;
grant usage,select on sequence public.salary_advance_requests_id_seq to authenticated;
grant usage,select on sequence public.weekly_payrolls_id_seq to authenticated;

drop policy if exists salary_advance_read on public.salary_advance_requests;
create policy salary_advance_read on public.salary_advance_requests for select to authenticated using (
  exists(select 1 from public.profiles p where p.user_id=(select auth.uid()) and p.business_id=salary_advance_requests.business_id and (p.role in ('owner','manager') or p.employee_id=salary_advance_requests.employee_id))
);
drop policy if exists salary_advance_create on public.salary_advance_requests;
create policy salary_advance_create on public.salary_advance_requests for insert to authenticated with check (
  exists(select 1 from public.profiles p where p.user_id=(select auth.uid()) and p.business_id=salary_advance_requests.business_id and (p.role in ('owner','manager') or (p.employee_id=salary_advance_requests.employee_id and p.status='active')))
);
drop policy if exists salary_advance_manage on public.salary_advance_requests;
create policy salary_advance_manage on public.salary_advance_requests for update to authenticated using (
  exists(select 1 from public.profiles p where p.user_id=(select auth.uid()) and p.business_id=salary_advance_requests.business_id and p.role in ('owner','manager'))
) with check (
  exists(select 1 from public.profiles p where p.user_id=(select auth.uid()) and p.business_id=salary_advance_requests.business_id and p.role in ('owner','manager'))
);

drop policy if exists weekly_payroll_read on public.weekly_payrolls;
create policy weekly_payroll_read on public.weekly_payrolls for select to authenticated using (
  exists(select 1 from public.profiles p where p.user_id=(select auth.uid()) and p.business_id=weekly_payrolls.business_id and (p.role in ('owner','manager') or p.employee_id=weekly_payrolls.employee_id))
);
drop policy if exists weekly_payroll_manage on public.weekly_payrolls;
create policy weekly_payroll_manage on public.weekly_payrolls for all to authenticated using (
  exists(select 1 from public.profiles p where p.user_id=(select auth.uid()) and p.business_id=weekly_payrolls.business_id and p.role in ('owner','manager'))
) with check (
  exists(select 1 from public.profiles p where p.user_id=(select auth.uid()) and p.business_id=weekly_payrolls.business_id and p.role in ('owner','manager'))
);
