-- Kho vé trò chơi tách riêng theo từng sân khấu.
-- Không phụ thuộc và không thay đổi dữ liệu kho vé Loto.

create table if not exists public.game_ticket_inventory (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id),
  venue_id bigint not null references public.venues(id),
  product_key text not null check (product_key in ('ticket_10k','ticket_20k','inflatable_20k','nlh_30k')),
  quantity_on_hand integer not null default 0 check (quantity_on_hand >= 0),
  last_counted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (business_id, venue_id, product_key)
);

create table if not exists public.game_ticket_inventory_transactions (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id),
  venue_id bigint not null references public.venues(id),
  product_key text not null check (product_key in ('ticket_10k','ticket_20k','inflatable_20k','nlh_30k')),
  transaction_type text not null check (transaction_type in ('stock_in','stock_count')),
  quantity_change integer not null,
  quantity_before integer not null check (quantity_before >= 0),
  quantity_after integer not null check (quantity_after >= 0),
  note text,
  created_by uuid not null default auth.uid(),
  created_at timestamptz not null default now()
);

create index if not exists game_ticket_inventory_venue_idx
  on public.game_ticket_inventory (business_id, venue_id);
create index if not exists game_ticket_inventory_transactions_venue_idx
  on public.game_ticket_inventory_transactions (business_id, venue_id, created_at desc);

alter table public.game_ticket_inventory enable row level security;
alter table public.game_ticket_inventory_transactions enable row level security;

drop policy if exists game_ticket_inventory_select on public.game_ticket_inventory;
create policy game_ticket_inventory_select on public.game_ticket_inventory
for select to authenticated
using (business_id = private.current_business_id() and private.can_access_venue(venue_id));

drop policy if exists game_ticket_inventory_write on public.game_ticket_inventory;
create policy game_ticket_inventory_write on public.game_ticket_inventory
for all to authenticated
using (business_id = private.current_business_id() and private.can_access_venue(venue_id) and private.current_role() in ('owner','manager'))
with check (business_id = private.current_business_id() and private.can_access_venue(venue_id) and private.current_role() in ('owner','manager'));

drop policy if exists game_ticket_inventory_transactions_select on public.game_ticket_inventory_transactions;
create policy game_ticket_inventory_transactions_select on public.game_ticket_inventory_transactions
for select to authenticated
using (business_id = private.current_business_id() and private.can_access_venue(venue_id));

drop policy if exists game_ticket_inventory_transactions_insert on public.game_ticket_inventory_transactions;
create policy game_ticket_inventory_transactions_insert on public.game_ticket_inventory_transactions
for insert to authenticated
with check (business_id = private.current_business_id() and private.can_access_venue(venue_id) and private.current_role() in ('owner','manager'));

create or replace function public.stock_in_game_tickets(
  p_venue_id bigint,
  p_items jsonb,
  p_note text default null
) returns setof public.game_ticket_inventory
language plpgsql
security invoker
set search_path = public, private
as $$
declare
  v_business_id bigint := private.current_business_id();
  v_item record;
  v_before integer;
  v_after integer;
begin
  if not private.can_access_venue(p_venue_id)
     or private.current_role() not in ('owner','manager')
     or not exists (
       select 1 from public.venues v
       where v.id=p_venue_id and v.business_id=v_business_id and v.is_active
     ) then
    raise exception 'Không có quyền nhập kho cho sân khấu này';
  end if;

  for v_item in
    select x.product_key, x.quantity
    from jsonb_to_recordset(coalesce(p_items, '[]'::jsonb)) as x(product_key text, quantity integer)
    where x.quantity > 0
  loop
    if v_item.product_key not in ('ticket_10k','ticket_20k','inflatable_20k','nlh_30k') then
      raise exception 'Loại vé trò chơi không hợp lệ';
    end if;

    insert into public.game_ticket_inventory (business_id, venue_id, product_key, quantity_on_hand)
    values (v_business_id, p_venue_id, v_item.product_key, 0)
    on conflict (business_id, venue_id, product_key) do nothing;

    select quantity_on_hand into v_before
    from public.game_ticket_inventory
    where business_id = v_business_id and venue_id = p_venue_id and product_key = v_item.product_key
    for update;

    v_after := v_before + v_item.quantity;
    update public.game_ticket_inventory
      set quantity_on_hand = v_after, updated_at = now()
      where business_id = v_business_id and venue_id = p_venue_id and product_key = v_item.product_key;

    insert into public.game_ticket_inventory_transactions
      (business_id, venue_id, product_key, transaction_type, quantity_change, quantity_before, quantity_after, note)
    values
      (v_business_id, p_venue_id, v_item.product_key, 'stock_in', v_item.quantity, v_before, v_after, nullif(trim(p_note),''));
  end loop;

  return query
    select * from public.game_ticket_inventory
    where business_id = v_business_id and venue_id = p_venue_id
    order by product_key;
end;
$$;

grant select on public.game_ticket_inventory to authenticated;
grant select, insert on public.game_ticket_inventory_transactions to authenticated;
grant execute on function public.stock_in_game_tickets(bigint,jsonb,text) to authenticated;
