insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('loto-area-attendance','loto-area-attendance',false,10485760,array['image/jpeg','image/png','image/webp'])
on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

create table if not exists public.loto_area_attendance(
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id),
  venue_id bigint not null references public.venues(id),
  work_date date not null,
  manager_user_id uuid not null references public.profiles(user_id),
  check_in_at timestamptz,
  check_in_photo_path text,
  check_out_at timestamptz,
  check_out_photo_path text,
  is_late boolean not null default false,
  late_reason text,
  approval_status text not null default 'not_required' check(approval_status in ('not_required','pending','approved','rejected')),
  reviewed_by uuid references public.profiles(user_id),
  reviewed_at timestamptz,
  review_note text,
  monthly_violation_no integer not null default 0,
  reminder_sent boolean not null default false,
  penalty_amount numeric not null default 0 check(penalty_amount>=0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(venue_id,work_date)
);
create index if not exists loto_area_attendance_business_idx on public.loto_area_attendance(business_id);
create index if not exists loto_area_attendance_manager_idx on public.loto_area_attendance(manager_user_id);
create index if not exists loto_area_attendance_reviewed_by_idx on public.loto_area_attendance(reviewed_by);
create index if not exists loto_area_attendance_month_idx on public.loto_area_attendance(venue_id,work_date,approval_status);

create table if not exists public.staff_notifications(
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id),
  user_id uuid not null references public.profiles(user_id),
  title text not null,
  content text not null,
  notification_type text not null default 'reminder',
  related_entity text,
  related_id bigint,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists staff_notifications_user_idx on public.staff_notifications(user_id,created_at desc);
create index if not exists staff_notifications_business_idx on public.staff_notifications(business_id);

alter table public.loto_area_attendance enable row level security;
alter table public.staff_notifications enable row level security;
drop policy if exists loto_area_attendance_management_read on public.loto_area_attendance;
create policy loto_area_attendance_management_read on public.loto_area_attendance for select to authenticated using(
  exists(select 1 from public.profiles p where p.user_id=(select auth.uid()) and p.business_id=loto_area_attendance.business_id and p.role in ('owner','manager'))
);
drop policy if exists staff_notifications_own_read on public.staff_notifications;
create policy staff_notifications_own_read on public.staff_notifications for select to authenticated using(user_id=(select auth.uid()));
grant select on public.loto_area_attendance,public.staff_notifications to authenticated;
