create table if not exists public.staff_time_off_requests (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id),
  employee_id bigint not null references public.employees(id),
  off_date date not null,
  week_start date not null,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  note text,
  created_by uuid not null references public.profiles(user_id),
  reviewed_by uuid references public.profiles(user_id),
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (business_id, employee_id, off_date)
);

create index if not exists staff_time_off_requests_week_idx on public.staff_time_off_requests(business_id,week_start,off_date);
create index if not exists staff_time_off_requests_employee_idx on public.staff_time_off_requests(employee_id,off_date);
create index if not exists staff_time_off_requests_created_by_idx on public.staff_time_off_requests(created_by);
create index if not exists staff_time_off_requests_reviewed_by_idx on public.staff_time_off_requests(reviewed_by);

alter table public.staff_time_off_requests enable row level security;
grant select,insert,update,delete on public.staff_time_off_requests to authenticated;
grant usage,select on sequence public.staff_time_off_requests_id_seq to authenticated;

drop policy if exists staff_time_off_requests_read on public.staff_time_off_requests;
create policy staff_time_off_requests_read on public.staff_time_off_requests for select to authenticated using (
  exists (
    select 1 from public.profiles p
    where p.user_id=(select auth.uid()) and p.business_id=staff_time_off_requests.business_id
      and (p.employee_id=staff_time_off_requests.employee_id or p.role in ('owner','manager'))
  )
);

drop policy if exists staff_time_off_requests_insert_own on public.staff_time_off_requests;
create policy staff_time_off_requests_insert_own on public.staff_time_off_requests for insert to authenticated with check (
  created_by=(select auth.uid()) and status='pending'
  and exists (
    select 1 from public.profiles p
    where p.user_id=(select auth.uid()) and p.business_id=staff_time_off_requests.business_id
      and (p.employee_id=staff_time_off_requests.employee_id or p.role='owner')
  )
);

drop policy if exists staff_time_off_requests_delete_own_pending on public.staff_time_off_requests;
create policy staff_time_off_requests_delete_own_pending on public.staff_time_off_requests for delete to authenticated using (
  created_by=(select auth.uid()) or exists (
    select 1 from public.profiles p
    where p.user_id=(select auth.uid()) and p.business_id=staff_time_off_requests.business_id and p.role='owner'
  )
);

drop policy if exists staff_time_off_requests_manage on public.staff_time_off_requests;
create policy staff_time_off_requests_manage on public.staff_time_off_requests for update to authenticated using (
  exists (
    select 1 from public.profiles p
    where p.user_id=(select auth.uid()) and p.business_id=staff_time_off_requests.business_id and p.role in ('owner','manager')
  )
) with check (
  exists (
    select 1 from public.profiles p
    where p.user_id=(select auth.uid()) and p.business_id=staff_time_off_requests.business_id and p.role in ('owner','manager')
  )
);
