create table if not exists public.weekly_staff_schedules (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id),
  venue_id bigint not null references public.venues(id),
  employee_id bigint not null references public.employees(id),
  work_date date not null,
  week_start date not null,
  note text,
  created_by uuid not null references public.profiles(user_id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (business_id,employee_id,work_date)
);

create index if not exists weekly_staff_schedules_week_idx on public.weekly_staff_schedules(business_id,week_start,venue_id);
create index if not exists weekly_staff_schedules_venue_date_idx on public.weekly_staff_schedules(venue_id,work_date);
create index if not exists weekly_staff_schedules_employee_idx on public.weekly_staff_schedules(employee_id,work_date);
create index if not exists weekly_staff_schedules_created_by_idx on public.weekly_staff_schedules(created_by);

alter table public.weekly_staff_schedules enable row level security;
grant select,insert,update,delete on public.weekly_staff_schedules to authenticated;
grant usage,select on sequence public.weekly_staff_schedules_id_seq to authenticated;

drop policy if exists weekly_staff_schedules_read on public.weekly_staff_schedules;
create policy weekly_staff_schedules_read on public.weekly_staff_schedules for select to authenticated using (
  exists (
    select 1 from public.profiles p where p.user_id=(select auth.uid())
      and p.business_id=weekly_staff_schedules.business_id
      and (p.role in ('owner','manager') or p.employee_id=weekly_staff_schedules.employee_id)
  )
);

drop policy if exists weekly_staff_schedules_manage on public.weekly_staff_schedules;
create policy weekly_staff_schedules_manage on public.weekly_staff_schedules for all to authenticated using (
  exists (
    select 1 from public.profiles p where p.user_id=(select auth.uid())
      and p.business_id=weekly_staff_schedules.business_id and p.role in ('owner','manager')
  )
) with check (
  exists (
    select 1 from public.profiles p where p.user_id=(select auth.uid())
      and p.business_id=weekly_staff_schedules.business_id and p.role in ('owner','manager')
  )
);
